Kort - Fyrsta PR fyrir jafningjarýni
Upplysingaverkfraedi/capstone-thestormlands pull request #2
Opened 2024-11-06 23:14 UTC by Benni47

fyrstu drögin af kortinu fyrir alla staðina. Á eftir að fínpússa og sameina með öllu hinu. Þarf að downloada pbxi skjalinu, hægt að skoða á preview á app.powerbi.com

2024-11-06 23:25 UTC, Valuringi03 requested changes
Fyrsta blaðsíðan er í rugli. Mátt taka hana út.

2024-11-06 23:27 UTC, Benni47 commented
ætti að vera búið að lagast

2024-11-06 23:27 UTC, Valuringi03 approved these changes
Flott

2024-11-07 08:38 UTC, GitGud069 approved these changes

2024-11-07 08:38 UTC, merged